# This is an example Secret manifest.
# 1. Rename this file to secret.yaml (or similar)
# 2. Replace the placeholder values below with your actual secrets, base64 encoded.
#    You can encode a value using: echo -n 'your-secret-value' | base64
# 3. Apply this manifest to your cluster: kubectl apply -f secret.yaml -n <your-namespace>
#
# The name of this secret should match the 'secretName' value in your values.yaml file.
# The default and recommended name for the shared secret is 'streamlink-secrets'.

apiVersion: v1
kind: Secret
metadata:
  # Ensure this name matches the 'secretName' in values.yaml (default: streamlink-secrets)
  name: streamlink-secrets
type: Opaque
data:
  # Required Twitch credentials (Base64 encoded)
  clientid: <base64_encoded_client_id> # e.g., echo -n 'your-client-id' | base64
  clientsecret: <base64_encoded_client_secret> # e.g., echo -n 'your-client-secret' | base64
  oauthtoken: <base64_encoded_oauth_token> # e.g., echo -n 'your-oauth-token' | base64

  # Optional Slack ID (Base64 encoded)
  # slackid: <base64_encoded_slack_id>

  # Optional Telegram credentials (Base64 encoded)
  telegrambottoken: <base64_encoded_telegram_bot_token>
  telegramchatid: <base64_encoded_telegram_chat_id>
