name: Build docker images with kaniko

on:
  push:
    branches: [ master ]
    tags:
      - '*'

jobs:
  deploy-ghcr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/metadata-action@v5
      id: metadata
      with:
        images: |
          ghcr.io/${{ github.repository }}
        tags: |
          type=ref,event=tag
          type=ref,event=branch,branch=master,compat=true
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: int128/kaniko-action@v1
      with:
        push: true
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}

  deploy-dockerio:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/metadata-action@v5
      id: metadata
      with:
        images: |
          docker.io/${{ github.repository }}
        tags: |
          type=ref,event=tag
          type=ref,event=branch,branch=master,compat=true
    - uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - uses: int128/kaniko-action@v1
      with:
        push: true
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}